openapi: 3.0.0
paths:
  /base_api/group/index:
    post:
      tags:
        - group
      description: 获取用户组列表
      operationId: 42e866cc59d359caa8c3ec0a4d0a851b
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
              type: object
      responses:
        '200':
          description: 成功返回
  /base_api/orders/pager:
    post:
      tags:
        - orders
      description: 订单分页
      operationId: a05f4e151e19ccf5dac56065a985cfad
      parameters:
        -
          name: order_num
          in: query
          description: 订单号
          required: false
        -
          name: wl_order_num
          in: query
          description: 运单号
          required: false
      responses:
        '0':
          description: 成功返回
          content:
            application/json:
              schema:
                type: object
              examples:
                '{code:0}':
                  description: ''
                  value: { code: 0, msg: 成功, data: [] }
  /base_api/user/index:
    post:
      tags:
        - user
      description: 获取用户列表
      operationId: e7e8bd2a376c36b327453d8aa2fadd7c
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
              type: object
      responses:
        '200':
          description: 成功返回
tags:
  -
    name: group
    description: 用户组
  -
    name: orders
    description: 订单
  -
    name: user
    description: 用户相关
